codigo = input("Código del equipo: ")
marca = input("Marca: ")
procesador = input("Procesador: ")
ram = input("Memoria RAM: ")
disco = input("Caoacidad del disco: ")
so = input("Sistema Operativo: ")
estado = input("Estado del equipo: ")

print("----- FICHA DEL COMPUTADOR -----")
print("Código: ", codigo)
print("Marca: ", marca)
print("Procesador: ", procesador)
print("Memoria RAM: ", ram)
print("Capacidad del disco: ", disco)
print("Sistema Operativo: ", so)
print("Estado del equipo: ", estado)
